Add boilerplate for the railroad scene
google/santa-tracker-web pull request #127
Opened 2023-10-27 19:46 UTC by Jezzamonn

No actual content yet, but should serve as a good example for how to add a new scene.

2023-10-28 00:59 UTC, menlocaleb requested changes

2023-10-28 00:59 UTC, menlocaleb commented on static/scenes/railroad/index.html
> +  <!-- Imports for Snowball -->
Nit: Update name of game?

2023-10-30 19:32 UTC, Jezzamonn commented on static/scenes/railroad/index.html
> +  <!-- Imports for Snowball -->
Good catch, updated!

2023-11-01 22:20 UTC, menlocaleb approved these changes

2023-11-01 23:32 UTC, merged